spring.application.name=assistance

spring.datasource.url=jdbc:postgresql://localhost:5432/mecano_db
spring.datasource.username=postgres
spring.datasource.password=1221Studi@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=change-this-secret-key-with-a-long-secure-value
jwt.expiration-ms=86400000
