package com.mecano.assistance.domain.model;

public enum Role {
    DRIVER,
    MECHANIC,
    GARAGE_ADMIN,
    ADMIN,
    SYSTEM_ADMIN,

    OPERATIONS_AGENT,
    OPERATIONS_MANAGER,

    SUPPORT_AGENT,
    SUPPORT_MANAGER,

    FINANCE_AGENT,
    FINANCE_MANAGER,

    SUPPLIER_VALIDATION_AGENT,
    SUPPLIER_VALIDATION_MANAGER
}